CREATE TABLE representative (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firt_name VARCHAR(100),
    last_name VARCHAR(100),
    phone VARCHAR(20),
    birth_date DATE,
    uuid_user VARCHAR(100),
    address VARCHAR(255),
    identification VARCHAR(20),
    nacionality VARCHAR(100),
    gender VARCHAR(10),
    image VARCHAR(255),
    deleted BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE
);
